services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "10001:8000"  # Map container's port to local host's port
    volumes:
      - ./backend:/app  # Mount local backend code
    depends_on:
      - db
      - pubsub
    environment:
      DATABASE_URL: "mysql://user:password@db:5010/mydatabase"
      PYTHONUNBUFFERED: 1  # Add this line to disable Python output buffering
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
      PUBSUB_PROJECT_ID: "local-project"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "10002:3000"
    volumes:
      - ./frontend:/app  # Mount local frontend code
      - /app/node_modules  # Preserve container node_modules
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:10002"

    # pubsub service

  db:
    image: mysql:latest
    ports:
      - "5010:5010"
    command: --port=5010
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8085"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
