services:
  mysql:
    image: mysql:8.0
    container_name: capstone-db
    restart: always
    env_file:
      - ./backend/.env  # ✅ Load credentials from the .env file
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: capstone-backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./backend/.env  # ✅ Load credentials from the .env file
    ports:
      - "5001:5000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:

