version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: capstone-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: capstone-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      pubsub-emulator:  # ✅ Added Pub/Sub dependency
        condition: service_started
    env_file:
      - ./backend/.env
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085  # ✅ Connect backend to emulator
    ports:
      - "5001:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend  # builds from the frontend folder
    container_name: capstone-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"  # expose Next.js on port 3000
    networks:
      - app-network
    volumes:
      - ./frontend:/app  # synced local frontend files with Docker

  pubsub-emulator:
    image: google/cloud-sdk:latest
    container_name: pubsub-emulator
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085  # Emulator's hostname within the network
    ports:
      - "8085:8085"
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085"] # Starts the emulator
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: