services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "9001:5000"  # Map container's port 5000 to host port 9001
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/mydatabase"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    ports:
      - "9002:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:9001"

  db:
    image: mysql:latest
    ports:
      - "9003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
