services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "10001:8000"  # Ensure backend listens on correct port
    volumes:
      - ./backend:/app  # App code only — init.sql removed
    depends_on:
      db:
        condition: service_healthy
      pubsub:
        condition: service_started
    environment:
      DB_URL: "mysql+mysqlconnector://user:password@db:3306/dnstwist_db"
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
      PUBSUB_PROJECT_ID: "local-project"
      PYTHONUNBUFFERED: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
      NODE_ENV: "development"
      NEXT_TELEMETRY_DISABLED: "1"

  db:
    image: mysql:8.0  # Ensure MySQL is version 8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dnstwist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    platform: linux/amd64
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

volumes:
  mysql_data: